spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: user_user
    password: user_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true