server:
  port: 8085
spring:
  application:
    name: activity-service
  datasource:
    url: jdbc:postgresql://localhost:5436/activitydb
    username: activity_user
    password: activity_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/